### ISSUE TITLE
Does not work with Jquery 3.2.1

### ISSUE THREAD

**Issue by haekb** [scronide/jquery.stackShuffle#2]
Documentation says it works with `jQuery 1.2.3 or later.`

However as replicated here https://jsfiddle.net/uuhuj32j/1/ I receive the error `TypeError: url.indexOf is not a function`

**Comment by scronide** [comment]
It was true at the time ;) until jQuery broke it by changing `.load()` to `.on('load', ...)`
